### ISSUE TITLE
Automatically hide long definitions using admonitions

### ISSUE THREAD

**Issue by fizruk** [rzk-lang/mkdocs-plugin-rzk#2]
The idea is to automatically hide definitions when they are "too large" (which can be configurable based on the number of lines). For example, here is what it might look like for [`is-natural-in-family-yon`](https://rzk-lang.github.io/sHoTT/simplicial-hott/09-yoneda.rzk/#define:is-natural-in-family-yon):

<img width="782" alt="Screenshot 2023-09-21 at 13 39 29" src="https://github.com/rzk-lang/mkdocs-plugin-rzk/assets/686582/44aad793-8c96-42f2-b216-c898aeca1adb">

The change should be purely text-based: separating a part of a block that starts with a line that contains a single `:=` and ends either with an end of a code block, or a non-empty line that is not indented. I think that should be enough.

Then, in `mkdocs.yml` we could have something like

```yaml
plugins:
  - rzk:
      collapse-large-definitions:
        min-lines: 4  # auto-collapse rendered definitions with 4+ lines (keeping statements/type signatures)
```
